[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
